# Generated by Django 2.2.16 on 2020-10-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_khfskjhfks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='khfskjhfks',
        ),
    ]
