# Generated by Django 2.2.16 on 2020-10-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20201015_0858"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="kjhfkhkhkghd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
