# Generated by Django 2.2.16 on 2020-10-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_kjhfkhkhkghd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='kjhfkhkhkghd',
        ),
    ]
